name: E2E Test
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to main & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
  push:
    branches:
      - main
      - release/**
jobs:
  test-fnsa-fnsa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Display go version
        run: go version
      - name: Test finschia to finschia
        run: |
          cd e2e
          make test-fnsa-fnsa
  test-fnsa-csms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Display go version
        run: go version
      - name: Test finschia to cosmos
        run: |
          cd e2e
          make test-fnsa-csms
